apiVersion: batch/v1
kind: Job
metadata:
  name: webserver-job
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/instance: webserver-job
    app.kubernetes.io/managed-by: yaml
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: webserver-job
        app.kubernetes.io/managed-by: yaml
    spec:
      containers:
      - name: webserver-job
        image: gcr.io/${PROJECT_ID}/webserver:latest
        args:
          - "-c"
          - "ls -la && sleep 120"
        command:
          - /bin/bash
      restartPolicy: Never