---
apiVersion: v1
kind: Service
metadata:
  name: webserver-service
spec:
  selector:
    app.kubernetes.io/instance: webserver-akhil
    app.kubernetes.io/version: "1.0.0"
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer